# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PeliasGeocoding/gui/PeliasMainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PeliasMainDialog(object):
    def setupUi(self, PeliasMainDialog):
        PeliasMainDialog.setObjectName("PeliasMainDialog")
        PeliasMainDialog.resize(460, 1014)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PeliasMainDialog.sizePolicy().hasHeightForWidth())
        PeliasMainDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(PeliasMainDialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label_15 = QtWidgets.QLabel(PeliasMainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setOpenExternalLinks(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 8, 1, 1, 1)
        self.search_tab = QtWidgets.QTabWidget(PeliasMainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_tab.sizePolicy().hasHeightForWidth())
        self.search_tab.setSizePolicy(sizePolicy)
        self.search_tab.setObjectName("search_tab")
        self.free_tab = QtWidgets.QWidget()
        self.free_tab.setObjectName("free_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.free_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_free_text = QgsFilterLineEdit(self.free_tab)
        self.search_free_text.setProperty("qgisRelation", "")
        self.search_free_text.setObjectName("search_free_text")
        self.verticalLayout.addWidget(self.search_free_text)
        self.label_13 = QtWidgets.QLabel(self.free_tab)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.search_tab.addTab(self.free_tab, "")
        self.struc_tab = QtWidgets.QWidget()
        self.struc_tab.setObjectName("struc_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.struc_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.struc_tab)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.search_struc_layers_group = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_struc_layers_group.sizePolicy().hasHeightForWidth())
        self.search_struc_layers_group.setSizePolicy(sizePolicy)
        self.search_struc_layers_group.setMinimumSize(QtCore.QSize(180, 0))
        self.search_struc_layers_group.setObjectName("search_struc_layers_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.search_struc_layers_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_struc_layers_text = QgsFilterLineEdit(self.search_struc_layers_group)
        self.search_struc_layers_text.setProperty("qgisRelation", "")
        self.search_struc_layers_text.setObjectName("search_struc_layers_text")
        self.verticalLayout_2.addWidget(self.search_struc_layers_text)
        self.label = QtWidgets.QLabel(self.search_struc_layers_group)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.search_struc_layers_combo = QtWidgets.QComboBox(self.search_struc_layers_group)
        self.search_struc_layers_combo.setObjectName("search_struc_layers_combo")
        self.search_struc_layers_combo.addItem("")
        self.search_struc_layers_combo.addItem("")
        self.search_struc_layers_combo.addItem("")
        self.search_struc_layers_combo.addItem("")
        self.search_struc_layers_combo.addItem("")
        self.search_struc_layers_combo.addItem("")
        self.search_struc_layers_combo.addItem("")
        self.search_struc_layers_combo.addItem("")
        self.verticalLayout_2.addWidget(self.search_struc_layers_combo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_4.addWidget(self.search_struc_layers_group, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.search_struc_add = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_struc_add.sizePolicy().hasHeightForWidth())
        self.search_struc_add.setSizePolicy(sizePolicy)
        self.search_struc_add.setMinimumSize(QtCore.QSize(30, 0))
        self.search_struc_add.setObjectName("search_struc_add")
        self.verticalLayout_3.addWidget(self.search_struc_add)
        self.search_struc_remove = QtWidgets.QPushButton(self.widget_2)
        self.search_struc_remove.setMinimumSize(QtCore.QSize(30, 0))
        self.search_struc_remove.setObjectName("search_struc_remove")
        self.verticalLayout_3.addWidget(self.search_struc_remove)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout_4.addWidget(self.widget_2, 0, 1, 1, 1)
        self.search_struc_list = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_struc_list.sizePolicy().hasHeightForWidth())
        self.search_struc_list.setSizePolicy(sizePolicy)
        self.search_struc_list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.search_struc_list.setObjectName("search_struc_list")
        self.gridLayout_4.addWidget(self.search_struc_list, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.search_tab.addTab(self.struc_tab, "")
        self.reverse_tab = QtWidgets.QWidget()
        self.reverse_tab.setObjectName("reverse_tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.reverse_tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.reverse_clear = QtWidgets.QPushButton(self.reverse_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reverse_clear.sizePolicy().hasHeightForWidth())
        self.reverse_clear.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("process-stop")
        self.reverse_clear.setIcon(icon)
        self.reverse_clear.setObjectName("reverse_clear")
        self.gridLayout_9.addWidget(self.reverse_clear, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.reverse_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.reverse_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 0, 3, 1, 1)
        self.reverse_map = QtWidgets.QPushButton(self.reverse_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reverse_map.sizePolicy().hasHeightForWidth())
        self.reverse_map.setSizePolicy(sizePolicy)
        self.reverse_map.setObjectName("reverse_map")
        self.gridLayout_9.addWidget(self.reverse_map, 0, 0, 1, 1)
        self.reverse_y = QgsFilterLineEdit(self.reverse_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reverse_y.sizePolicy().hasHeightForWidth())
        self.reverse_y.setSizePolicy(sizePolicy)
        self.reverse_y.setMaximumSize(QtCore.QSize(120, 25))
        self.reverse_y.setProperty("qgisRelation", "")
        self.reverse_y.setObjectName("reverse_y")
        self.gridLayout_9.addWidget(self.reverse_y, 0, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(89, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 0, 5, 1, 1)
        self.reverse_x = QgsFilterLineEdit(self.reverse_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reverse_x.sizePolicy().hasHeightForWidth())
        self.reverse_x.setSizePolicy(sizePolicy)
        self.reverse_x.setMaximumSize(QtCore.QSize(120, 25))
        self.reverse_x.setProperty("qgisRelation", "")
        self.reverse_x.setObjectName("reverse_x")
        self.gridLayout_9.addWidget(self.reverse_x, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 2, 0, 1, 1)
        self.search_tab.addTab(self.reverse_tab, "")
        self.batch_tab = QtWidgets.QWidget()
        self.batch_tab.setObjectName("batch_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.batch_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.batch_free = QtWidgets.QPushButton(self.batch_tab)
        self.batch_free.setObjectName("batch_free")
        self.horizontalLayout_2.addWidget(self.batch_free, 0, QtCore.Qt.AlignTop)
        self.batch_structured = QtWidgets.QPushButton(self.batch_tab)
        self.batch_structured.setObjectName("batch_structured")
        self.horizontalLayout_2.addWidget(self.batch_structured, 0, QtCore.Qt.AlignTop)
        self.batch_reverse = QtWidgets.QPushButton(self.batch_tab)
        self.batch_reverse.setObjectName("batch_reverse")
        self.horizontalLayout_2.addWidget(self.batch_reverse, 0, QtCore.Qt.AlignTop)
        self.search_tab.addTab(self.batch_tab, "")
        self.gridLayout.addWidget(self.search_tab, 2, 0, 1, 3)
        self.search_filters_group = QgsCollapsibleGroupBox(PeliasMainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_filters_group.sizePolicy().hasHeightForWidth())
        self.search_filters_group.setSizePolicy(sizePolicy)
        self.search_filters_group.setSaveCollapsedState(False)
        self.search_filters_group.setObjectName("search_filters_group")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.search_filters_group)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.search_filters_group)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.search_filters_sources_combo = QgsCheckableComboBox(self.search_filters_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_filters_sources_combo.sizePolicy().hasHeightForWidth())
        self.search_filters_sources_combo.setSizePolicy(sizePolicy)
        self.search_filters_sources_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.search_filters_sources_combo.setCurrentText("")
        self.search_filters_sources_combo.setObjectName("search_filters_sources_combo")
        self.search_filters_sources_combo.addItem("")
        self.search_filters_sources_combo.addItem("")
        self.search_filters_sources_combo.addItem("")
        self.search_filters_sources_combo.addItem("")
        self.gridLayout_3.addWidget(self.search_filters_sources_combo, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.search_filters_group)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.search_filters_layer_combo = QgsCheckableComboBox(self.search_filters_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_filters_layer_combo.sizePolicy().hasHeightForWidth())
        self.search_filters_layer_combo.setSizePolicy(sizePolicy)
        self.search_filters_layer_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.search_filters_layer_combo.setCurrentText("")
        self.search_filters_layer_combo.setObjectName("search_filters_layer_combo")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.search_filters_layer_combo.addItem("")
        self.gridLayout_3.addWidget(self.search_filters_layer_combo, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.search_filters_group, 6, 0, 1, 3)
        self.search_rest_group = QgsCollapsibleGroupBox(PeliasMainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_group.sizePolicy().hasHeightForWidth())
        self.search_rest_group.setSizePolicy(sizePolicy)
        self.search_rest_group.setSaveCollapsedState(False)
        self.search_rest_group.setObjectName("search_rest_group")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.search_rest_group)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.search_rest_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.search_rest_country = QgsFilterLineEdit(self.search_rest_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_country.sizePolicy().hasHeightForWidth())
        self.search_rest_country.setSizePolicy(sizePolicy)
        self.search_rest_country.setProperty("qgisRelation", "")
        self.search_rest_country.setObjectName("search_rest_country")
        self.gridLayout_5.addWidget(self.search_rest_country, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_16 = QtWidgets.QLabel(self.search_rest_group)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 2, 2, 1, 1)
        self.limit_value = QtWidgets.QSpinBox(self.search_rest_group)
        self.limit_value.setMinimum(1)
        self.limit_value.setMaximum(50)
        self.limit_value.setProperty("value", 5)
        self.limit_value.setObjectName("limit_value")
        self.gridLayout_5.addWidget(self.limit_value, 2, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 2, 4, 1, 1)
        self.search_rest_circle_group = QtWidgets.QGroupBox(self.search_rest_group)
        self.search_rest_circle_group.setObjectName("search_rest_circle_group")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.search_rest_circle_group)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_12 = QtWidgets.QLabel(self.search_rest_circle_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 3, 1, 1)
        self.search_rest_circle_button = QtWidgets.QPushButton(self.search_rest_circle_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_circle_button.sizePolicy().hasHeightForWidth())
        self.search_rest_circle_button.setSizePolicy(sizePolicy)
        self.search_rest_circle_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.search_rest_circle_button.setObjectName("search_rest_circle_button")
        self.gridLayout_7.addWidget(self.search_rest_circle_button, 0, 0, 1, 1)
        self.search_rest_circle_label = QtWidgets.QLabel(self.search_rest_circle_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_circle_label.sizePolicy().hasHeightForWidth())
        self.search_rest_circle_label.setSizePolicy(sizePolicy)
        self.search_rest_circle_label.setObjectName("search_rest_circle_label")
        self.gridLayout_7.addWidget(self.search_rest_circle_label, 0, 1, 1, 1)
        self.search_rest_circle_y = QgsFilterLineEdit(self.search_rest_circle_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_circle_y.sizePolicy().hasHeightForWidth())
        self.search_rest_circle_y.setSizePolicy(sizePolicy)
        self.search_rest_circle_y.setMaximumSize(QtCore.QSize(120, 25))
        self.search_rest_circle_y.setProperty("qgisRelation", "")
        self.search_rest_circle_y.setObjectName("search_rest_circle_y")
        self.gridLayout_7.addWidget(self.search_rest_circle_y, 0, 4, 1, 1)
        self.search_rest_circle_x = QgsFilterLineEdit(self.search_rest_circle_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_circle_x.sizePolicy().hasHeightForWidth())
        self.search_rest_circle_x.setSizePolicy(sizePolicy)
        self.search_rest_circle_x.setMaximumSize(QtCore.QSize(120, 25))
        self.search_rest_circle_x.setClearButtonEnabled(False)
        self.search_rest_circle_x.setProperty("qgisRelation", "")
        self.search_rest_circle_x.setObjectName("search_rest_circle_x")
        self.gridLayout_7.addWidget(self.search_rest_circle_x, 0, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem8, 0, 5, 1, 1)
        self.search_rest_circle_clear = QtWidgets.QPushButton(self.search_rest_circle_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_circle_clear.sizePolicy().hasHeightForWidth())
        self.search_rest_circle_clear.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("process-stop")
        self.search_rest_circle_clear.setIcon(icon)
        self.search_rest_circle_clear.setObjectName("search_rest_circle_clear")
        self.gridLayout_7.addWidget(self.search_rest_circle_clear, 1, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.search_rest_circle_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.search_rest_circle_value = QtWidgets.QSpinBox(self.widget_3)
        self.search_rest_circle_value.setMaximum(100)
        self.search_rest_circle_value.setProperty("value", 10)
        self.search_rest_circle_value.setObjectName("search_rest_circle_value")
        self.horizontalLayout.addWidget(self.search_rest_circle_value)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.gridLayout_7.addWidget(self.widget_3, 1, 1, 1, 5)
        self.gridLayout_5.addWidget(self.search_rest_circle_group, 1, 0, 1, 5)
        self.search_rest_rect_group = QtWidgets.QGroupBox(self.search_rest_group)
        self.search_rest_rect_group.setObjectName("search_rest_rect_group")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.search_rest_rect_group)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.search_rest_rect_group)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.search_rest_rect_group)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 3, 1, 1)
        self.search_rest_rect_xmin = QgsFilterLineEdit(self.search_rest_rect_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_rect_xmin.sizePolicy().hasHeightForWidth())
        self.search_rest_rect_xmin.setSizePolicy(sizePolicy)
        self.search_rest_rect_xmin.setMaximumSize(QtCore.QSize(120, 25))
        self.search_rest_rect_xmin.setProperty("qgisRelation", "")
        self.search_rest_rect_xmin.setObjectName("search_rest_rect_xmin")
        self.gridLayout_6.addWidget(self.search_rest_rect_xmin, 0, 2, 1, 1)
        self.search_rest_rect_label = QtWidgets.QLabel(self.search_rest_rect_group)
        self.search_rest_rect_label.setObjectName("search_rest_rect_label")
        self.gridLayout_6.addWidget(self.search_rest_rect_label, 0, 1, 1, 1)
        self.search_rest_rect_ymin = QgsFilterLineEdit(self.search_rest_rect_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_rect_ymin.sizePolicy().hasHeightForWidth())
        self.search_rest_rect_ymin.setSizePolicy(sizePolicy)
        self.search_rest_rect_ymin.setMaximumSize(QtCore.QSize(120, 25))
        self.search_rest_rect_ymin.setProperty("qgisRelation", "")
        self.search_rest_rect_ymin.setObjectName("search_rest_rect_ymin")
        self.gridLayout_6.addWidget(self.search_rest_rect_ymin, 0, 4, 1, 1)
        self.search_rest_rect_xmax = QgsFilterLineEdit(self.search_rest_rect_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_rect_xmax.sizePolicy().hasHeightForWidth())
        self.search_rest_rect_xmax.setSizePolicy(sizePolicy)
        self.search_rest_rect_xmax.setMaximumSize(QtCore.QSize(120, 25))
        self.search_rest_rect_xmax.setProperty("qgisRelation", "")
        self.search_rest_rect_xmax.setObjectName("search_rest_rect_xmax")
        self.gridLayout_6.addWidget(self.search_rest_rect_xmax, 1, 2, 1, 1)
        self.search_rest_rect_ymax = QgsFilterLineEdit(self.search_rest_rect_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_rect_ymax.sizePolicy().hasHeightForWidth())
        self.search_rest_rect_ymax.setSizePolicy(sizePolicy)
        self.search_rest_rect_ymax.setMaximumSize(QtCore.QSize(120, 25))
        self.search_rest_rect_ymax.setProperty("qgisRelation", "")
        self.search_rest_rect_ymax.setObjectName("search_rest_rect_ymax")
        self.gridLayout_6.addWidget(self.search_rest_rect_ymax, 1, 4, 1, 1)
        self.search_rest_rect_button = QtWidgets.QPushButton(self.search_rest_rect_group)
        self.search_rest_rect_button.setObjectName("search_rest_rect_button")
        self.gridLayout_6.addWidget(self.search_rest_rect_button, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.search_rest_rect_group)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 1, 3, 1, 1)
        self.search_rest_rect_clear = QtWidgets.QPushButton(self.search_rest_rect_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_rest_rect_clear.sizePolicy().hasHeightForWidth())
        self.search_rest_rect_clear.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("process-stop")
        self.search_rest_rect_clear.setIcon(icon)
        self.search_rest_rect_clear.setObjectName("search_rest_rect_clear")
        self.gridLayout_6.addWidget(self.search_rest_rect_clear, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_5.addWidget(self.search_rest_rect_group, 0, 0, 1, 5)
        self.gridLayout.addWidget(self.search_rest_group, 5, 0, 1, 3)
        self.help_button = QtWidgets.QPushButton(PeliasMainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_button.sizePolicy().hasHeightForWidth())
        self.help_button.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("help")
        self.help_button.setIcon(icon)
        self.help_button.setObjectName("help_button")
        self.gridLayout.addWidget(self.help_button, 8, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(PeliasMainDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 8, 2, 1, 1)
        self.search_focus_group = QgsCollapsibleGroupBox(PeliasMainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_focus_group.sizePolicy().hasHeightForWidth())
        self.search_focus_group.setSizePolicy(sizePolicy)
        self.search_focus_group.setSaveCollapsedState(False)
        self.search_focus_group.setObjectName("search_focus_group")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.search_focus_group)
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.search_focus_button = QtWidgets.QPushButton(self.search_focus_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_focus_button.sizePolicy().hasHeightForWidth())
        self.search_focus_button.setSizePolicy(sizePolicy)
        self.search_focus_button.setObjectName("search_focus_button")
        self.gridLayout_8.addWidget(self.search_focus_button, 0, 0, 1, 1)
        self.search_focus_y = QgsFilterLineEdit(self.search_focus_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_focus_y.sizePolicy().hasHeightForWidth())
        self.search_focus_y.setSizePolicy(sizePolicy)
        self.search_focus_y.setMaximumSize(QtCore.QSize(120, 25))
        self.search_focus_y.setProperty("qgisRelation", "")
        self.search_focus_y.setObjectName("search_focus_y")
        self.gridLayout_8.addWidget(self.search_focus_y, 0, 4, 1, 1)
        self.search_focus_x = QgsFilterLineEdit(self.search_focus_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_focus_x.sizePolicy().hasHeightForWidth())
        self.search_focus_x.setSizePolicy(sizePolicy)
        self.search_focus_x.setMaximumSize(QtCore.QSize(120, 25))
        self.search_focus_x.setProperty("qgisRelation", "")
        self.search_focus_x.setObjectName("search_focus_x")
        self.gridLayout_8.addWidget(self.search_focus_x, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.search_focus_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.search_focus_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 0, 3, 1, 1)
        self.search_focus_clear = QtWidgets.QPushButton(self.search_focus_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_focus_clear.sizePolicy().hasHeightForWidth())
        self.search_focus_clear.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("process-stop")
        self.search_focus_clear.setIcon(icon)
        self.search_focus_clear.setObjectName("search_focus_clear")
        self.gridLayout_8.addWidget(self.search_focus_clear, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem10, 0, 5, 1, 1)
        self.gridLayout.addWidget(self.search_focus_group, 3, 0, 1, 3)
        self.widget_4 = QtWidgets.QWidget(PeliasMainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.provider_combo = QtWidgets.QComboBox(self.widget_4)
        self.provider_combo.setObjectName("provider_combo")
        self.horizontalLayout_3.addWidget(self.provider_combo)
        self.provider_refresh = QtWidgets.QPushButton(self.widget_4)
        self.provider_refresh.setText("")
        icon = QtGui.QIcon.fromTheme("reload")
        self.provider_refresh.setIcon(icon)
        self.provider_refresh.setObjectName("provider_refresh")
        self.horizontalLayout_3.addWidget(self.provider_refresh)
        self.provider_config = QtWidgets.QPushButton(self.widget_4)
        self.provider_config.setText("")
        icon = QtGui.QIcon.fromTheme("emblem-system")
        self.provider_config.setIcon(icon)
        self.provider_config.setObjectName("provider_config")
        self.horizontalLayout_3.addWidget(self.provider_config)
        self.debug_check = QtWidgets.QCheckBox(self.widget_4)
        self.debug_check.setObjectName("debug_check")
        self.horizontalLayout_3.addWidget(self.debug_check)
        self.horizontalLayout_3.setStretch(1, 5)
        self.gridLayout.addWidget(self.widget_4, 1, 0, 1, 3)
        self.debug_text = QtWidgets.QTextBrowser(PeliasMainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.debug_text.sizePolicy().hasHeightForWidth())
        self.debug_text.setSizePolicy(sizePolicy)
        self.debug_text.setMaximumSize(QtCore.QSize(16777215, 80))
        self.debug_text.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.debug_text.setOpenExternalLinks(True)
        self.debug_text.setObjectName("debug_text")
        self.gridLayout.addWidget(self.debug_text, 7, 0, 1, 3)

        self.retranslateUi(PeliasMainDialog)
        self.search_tab.setCurrentIndex(0)
        self.buttonBox.accepted.connect(PeliasMainDialog.accept)
        self.buttonBox.rejected.connect(PeliasMainDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PeliasMainDialog)

    def retranslateUi(self, PeliasMainDialog):
        _translate = QtCore.QCoreApplication.translate
        PeliasMainDialog.setWindowTitle(_translate("PeliasMainDialog", "Pelias Geocoding"))
        self.label_15.setText(_translate("PeliasMainDialog", "<html><head/><body><p align=middle>Provided by <a href=\"https://gis-ops.com\"><img src=\":/plugins/PeliasTools/gui/img/logo_gisops_300.png\" width=100/></a></p></body></html>"))
        self.label_13.setText(_translate("PeliasMainDialog", "<html><body><div style=\"line-height: 150%\"><p><span style=\" font-weight:600;\">Note</span>, address expansion is not supported at this time, i.e. Main Street/Hauptstraße instead of Main St/Haupstr..</p></div></body></html>"))
        self.search_tab.setTabText(self.search_tab.indexOf(self.free_tab), _translate("PeliasMainDialog", "Free Text"))
        self.search_struc_layers_group.setTitle(_translate("PeliasMainDialog", "Add layers"))
        self.label.setText(_translate("PeliasMainDialog", "Add to layer"))
        self.search_struc_layers_combo.setItemText(0, _translate("PeliasMainDialog", "address"))
        self.search_struc_layers_combo.setItemText(1, _translate("PeliasMainDialog", "neighbourhood"))
        self.search_struc_layers_combo.setItemText(2, _translate("PeliasMainDialog", "borough"))
        self.search_struc_layers_combo.setItemText(3, _translate("PeliasMainDialog", "locality"))
        self.search_struc_layers_combo.setItemText(4, _translate("PeliasMainDialog", "county"))
        self.search_struc_layers_combo.setItemText(5, _translate("PeliasMainDialog", "region"))
        self.search_struc_layers_combo.setItemText(6, _translate("PeliasMainDialog", "postalcode"))
        self.search_struc_layers_combo.setItemText(7, _translate("PeliasMainDialog", "country"))
        self.search_struc_add.setText(_translate("PeliasMainDialog", ">"))
        self.search_struc_remove.setText(_translate("PeliasMainDialog", "<"))
        self.search_tab.setTabText(self.search_tab.indexOf(self.struc_tab), _translate("PeliasMainDialog", "Structured"))
        self.reverse_clear.setText(_translate("PeliasMainDialog", " Clear"))
        self.label_18.setText(_translate("PeliasMainDialog", "X"))
        self.label_17.setText(_translate("PeliasMainDialog", "Y"))
        self.reverse_map.setText(_translate("PeliasMainDialog", "Map!"))
        self.search_tab.setTabText(self.search_tab.indexOf(self.reverse_tab), _translate("PeliasMainDialog", "Reverse"))
        self.batch_free.setText(_translate("PeliasMainDialog", "Free Text"))
        self.batch_structured.setText(_translate("PeliasMainDialog", "Structured"))
        self.batch_reverse.setText(_translate("PeliasMainDialog", "Reverse"))
        self.search_tab.setTabText(self.search_tab.indexOf(self.batch_tab), _translate("PeliasMainDialog", "Batch jobs"))
        self.search_filters_group.setTitle(_translate("PeliasMainDialog", "Filters"))
        self.label_8.setText(_translate("PeliasMainDialog", "Sources"))
        self.search_filters_sources_combo.setItemText(0, _translate("PeliasMainDialog", "osm"))
        self.search_filters_sources_combo.setItemText(1, _translate("PeliasMainDialog", "oa"))
        self.search_filters_sources_combo.setItemText(2, _translate("PeliasMainDialog", "wof"))
        self.search_filters_sources_combo.setItemText(3, _translate("PeliasMainDialog", "gn"))
        self.label_9.setText(_translate("PeliasMainDialog", "Layers"))
        self.search_filters_layer_combo.setItemText(0, _translate("PeliasMainDialog", "venue"))
        self.search_filters_layer_combo.setItemText(1, _translate("PeliasMainDialog", "address"))
        self.search_filters_layer_combo.setItemText(2, _translate("PeliasMainDialog", "street"))
        self.search_filters_layer_combo.setItemText(3, _translate("PeliasMainDialog", "neighbourhood"))
        self.search_filters_layer_combo.setItemText(4, _translate("PeliasMainDialog", "borough"))
        self.search_filters_layer_combo.setItemText(5, _translate("PeliasMainDialog", "localadmin"))
        self.search_filters_layer_combo.setItemText(6, _translate("PeliasMainDialog", "locality"))
        self.search_filters_layer_combo.setItemText(7, _translate("PeliasMainDialog", "county"))
        self.search_filters_layer_combo.setItemText(8, _translate("PeliasMainDialog", "macrocounty"))
        self.search_filters_layer_combo.setItemText(9, _translate("PeliasMainDialog", "region"))
        self.search_filters_layer_combo.setItemText(10, _translate("PeliasMainDialog", "macroregion"))
        self.search_filters_layer_combo.setItemText(11, _translate("PeliasMainDialog", "country"))
        self.search_filters_layer_combo.setItemText(12, _translate("PeliasMainDialog", "coarse"))
        self.search_rest_group.setTitle(_translate("PeliasMainDialog", "Restrictions"))
        self.label_3.setText(_translate("PeliasMainDialog", "Country"))
        self.search_rest_country.setToolTip(_translate("PeliasMainDialog", "ISO 3166-1 alpha-3 country codes, e.g. GBR, DEU, USA.."))
        self.search_rest_country.setPlaceholderText(_translate("PeliasMainDialog", "DEU"))
        self.label_16.setText(_translate("PeliasMainDialog", "Limit features to"))
        self.search_rest_circle_group.setTitle(_translate("PeliasMainDialog", "Circle"))
        self.label_12.setText(_translate("PeliasMainDialog", "Y"))
        self.search_rest_circle_button.setToolTip(_translate("PeliasMainDialog", "<html><head/><body><p>Set a point from map canvas.</p></body></html>"))
        self.search_rest_circle_button.setText(_translate("PeliasMainDialog", "Map!"))
        self.search_rest_circle_label.setText(_translate("PeliasMainDialog", "X"))
        self.search_rest_circle_clear.setText(_translate("PeliasMainDialog", " Clear"))
        self.label_6.setText(_translate("PeliasMainDialog", "Radius"))
        self.label_7.setText(_translate("PeliasMainDialog", "km"))
        self.search_rest_rect_group.setTitle(_translate("PeliasMainDialog", "Rectangle"))
        self.label_10.setText(_translate("PeliasMainDialog", "Xmax"))
        self.label_5.setText(_translate("PeliasMainDialog", "Ymin"))
        self.search_rest_rect_label.setText(_translate("PeliasMainDialog", "Xmin"))
        self.search_rest_rect_button.setToolTip(_translate("PeliasMainDialog", "<html><head/><body><p>Drag a rectangle in maps canvas.</p></body></html>"))
        self.search_rest_rect_button.setText(_translate("PeliasMainDialog", "Map!"))
        self.label_11.setText(_translate("PeliasMainDialog", "Ymax"))
        self.search_rest_rect_clear.setText(_translate("PeliasMainDialog", "  Clear"))
        self.help_button.setText(_translate("PeliasMainDialog", "  Help"))
        self.search_focus_group.setTitle(_translate("PeliasMainDialog", "Focus Point"))
        self.search_focus_button.setText(_translate("PeliasMainDialog", "Map!"))
        self.label_2.setText(_translate("PeliasMainDialog", "X"))
        self.label_4.setText(_translate("PeliasMainDialog", "Y"))
        self.search_focus_clear.setText(_translate("PeliasMainDialog", " Clear"))
        self.label_14.setText(_translate("PeliasMainDialog", "Provider"))
        self.debug_check.setToolTip(_translate("PeliasMainDialog", "<html><head/><body><p>When set, will include all <i>id, gid</id> fields in the resulting GeoJSON and print the query in a text box below.</p></body></html>"))
        self.debug_check.setText(_translate("PeliasMainDialog", "Debug"))
        self.debug_text.setPlaceholderText(_translate("PeliasMainDialog", "Queries and errors will be printed here."))

from qgscheckablecombobox import QgsCheckableComboBox
from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgsfilterlineedit import QgsFilterLineEdit
from . import resources_rc
